### ISSUE TITLE
Git LFS is private

### ISSUE THREAD

**Issue by lordofwaterandwisdom** [Gfurst/Jack-o-Nine-2#45]
I understand that hosting LFS yourself is the only way to use LFS for free and that you might not want unrestricted access to your LFS server.

However, it is quite hard to contribute to a public project, if half the project is private.

I do not see any elegant solution to this (at least not one that is free), but perhaps you could provide a MEGA link to the whole source zip or something like that?
That way one can copy-paste the relevant files into the newest version of the project. Not ideal, but at least it still allows for open source contributions.

**Comment by Gfurst** [comment]
The project isn't private, the LFS is because of content sensitive material, but the thing is that authentication is required (since its a separate host).
How did you come about to know the project? Cause on the same places you can find the authentication for it. However it may be the case where the ip addresses are out of date, I'll update it soon enough.
Anyway, interesting in helping?

**Comment by lordofwaterandwisdom** [comment]
You are correct, my mistake. Information regarding this project could be more centralized.

As for wether or not I'm going to help. I would like to and I have about a month more of free time before my summer break ends.

As such I am willing to help right now, but your time would probably be better spent writing proper documentation, than "training or introducing" me specifically to the project, as I can make no promises for the time that follows summer break.

As for my qualifications:
I have been playing around a little with Godot, before this project.
![output](https://user-images.githubusercontent.com/30572029/28888390-b2ad8c9c-77c0-11e7-8ea3-74001954cda6.gif)


I would primarily be interested in programming, but I could probably also do some of the "manual labour" like moving body parts around in GIMP, if necessary.

While you have documented several tasks in Githubs issue tracker, they are very sparsely described. Do you have anything specific in mind, if I were to contribute?

**Comment by lordofwaterandwisdom** [comment]
So I have forked the repo and experimented a little (https://github.com/lordofwaterandwisdom/Jack-o-Nine-2).

I have made a lot of changes to your approach (at some places ignoring it entirely or writing duplicate code, this is of course not desirable and not my end goal).

Primary deviations include:
I wasn't entirely sure on what naming scheme you use, so I went ahead and changed everything to my own preferences (Should we choose to work together, I will of course respect whatever we decide upon)
I changed the JSON format so that the file path is the name of the scene, and that each scene can refer to other scenes through relative path
I circumvent preloading (I did it out of convenience, but now that I have done it I am not sure if preloading JSON is actually necessary)
I moved some folders around
I redid SceneA and called it MainGame (I would like to know what the significance of the name sceneA is?)
SceneA now has two subtrees DialogPanel and NavigationMenu

I have deliberately not made a PR, as a lot of the changes are subjective.

Please share your thoughts.

**Comment by Gfurst** [comment]
if the guy is still watching this at all, I've made the move to gitgud, I've already did most of the migration now I'm remaking the issues, in any case, you had some good ideas, should you wish to help with the project again, search it up
